---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-argocd-example-build-deploy-pipeline
spec:
  resources:
    - name: git-app-repo
      type: git
    - name: image-registry
      type: image
  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/git-app-repo
      resources:
        inputs:
          - name: git-app-repo
            resource: git-app-repo
        outputs:
          - name: image-registry
            resource: image-registry
    - name: sync-application
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - build-docker-image
      params:
        - name: flags
          value: --insecure # needed in this example only because the Argo CD server is locally hosted